#!/bin/sh

set -e

QUERY=$1
if [ "$QUERY" = "" ]; then
    echo "Usage: alc query"
    exit 1
fi

url=$(printf 'http://eow.alc.co.jp/search?q=%s&ref=sa' $QUERY)

OS=$(uname)
if [ "$OS" = "Linux" ]; then
    xdg-open $url > /dev/null 2>&1
else
    open $url
fi
