#!/bin/sh
set -e

FILE=$1

TEST_DEP=
if [ "$FILE" = "--test" ]; then
    TEST_DEP=1
    FILE=$2
fi

if [ "$FILE" != "" -a ! -e "$FILE" ]; then
    echo "'$FILE' is not existed"
    exit 1
fi

echo "(source gnu)" > Cask
echo "(source melpa)" >> Cask
echo "" >> Cask

if [ "$FILE" != "" ]; then
    echo "(package-file" '"'$FILE'"'")" >> Cask
fi

if [ ! -z $TEST_DEP ]; then
    cat <<EOF >> Cask

(development
 (depends-on "ert"))
EOF
fi
