#!/usr/bin/env bash
set -e

FILE=$1

if [[ "$FILE" == "" ]]; then
  echo "Usage: gencask elisp_file"
  exit 1
fi

if [[ ! -e "$FILE" ]]; then
  echo "Error: '$FILE' is not existed"
  exit 1
fi

cat <<EOF >Cask
(source gnu)
(source melpa)

EOF

echo "(package-file \"$FILE\")" >> Cask
