#!/bin/sh

set -e

url=""

REMOTE=$1
if [ "$REMOTE" = "" ]; then
    REMOTE=origin
fi

URL_PATH=$(git remote -v | grep -m 1 $REMOTE \
       | perl -awln -e '$F[1] =~ m{github.com[:/]?(\S+?)?(?:\.git)?$} and print $1')

branch=$(git symbolic-ref HEAD| perl -wpe 's{refs/heads/}{}')
if [ $branch = "master" ];then
    url="https://github.com/$URL_PATH"
else
    url="https://github.com/$URL_PATH/tree/${branch}"
fi

OS=$(uname)
if [ "$OS" = "Linux" ]; then
    xdg-open $url >/dev/null 2>&1
else
    open $url
fi
