#!/bin/sh

set -e

url=""

if [ "$1" = "" ]; then
    REMOTE=$(git remote -v | grep -m 1 origin \
        | perl -awln -e '$F[1] =~ m{github.com[:/]?(\S+)?\.git} and print $1')

    url="https://github.com/$REMOTE"
else
    url="https://github.com/$1"
fi

if which xdg-open > /dev/null 2>&1; then
    xdg-open $url
fi
