#!/bin/sh
set -e

branch=$(git branch -a | perl -wln -e 'm{\s+remotes/(\S+)$} and print $1' | peco)
if [ "$branch" = "" ]; then
    exit
fi

local_branch=$(echo $branch | perl -wln -e 'm{[^/]+/(.+)} and print $1')
if [ "$local_branch" = "" ]; then
    exit
fi

echo "Checkout $local_branch"
git checkout -b $local_branch $branch
