#!/usr/bin/env zsh

set -e

go_packages=("builtin" "unsafe")

for dir in $GOROOT $(perl -wle 'print $_ for split q{:}, shift' $GOPATH)
do
    pkgdir="$dir/pkg"
    if [ -d $pkgdir ]; then
        packages=$(find $pkgdir -name "*.a" -type f \
                          | perl -wlp -e "s{$pkgdir/(?:(?:obj|tool)/)?[^/]+/}{} and s{\\.a\$}{}")
        go_packages=($packages $go_packages)
    fi
done

PACKAGE=$(print -l $go_packages | grep -v Godeps | sort | uniq | peco)
if [ "$PACKAGE" != "" ];then
    $GOROOT/bin/godoc $PACKAGE | $PAGER
fi
