#!/usr/bin/env bash

set -e

PACKAGE=$(gopkgs | grep -v internal | sort -u | peco)
if [[ "$PACKAGE" != "" ]];then
    if [[ -z "$GOROOT" ]]; then
        godoc $PACKAGE | $PAGER
    else
        $GOROOT/bin/godoc $PACKAGE | $PAGER
    fi
fi
