#!/usr/bin/env bash
set -e

IDE_NAME=$1
if [[ $IDE_NAME == "" ]]; then
    echo "usage: ide ide_name"
    exit 1
fi

if ! command -v "$IDE_NAME" 1>/dev/null 2>/dev/null; then
    echo "IDE '$IDE_NAME' is not installed"
    exit 1
fi

"$IDE_NAME" . 1>/dev/null 2>/dev/null &
