#!/bin/sh
# -*- mode:shell-script -*-

set -e

if ! which curl > /dev/null 2>&1 ; then
    echo "Please install curl"
    exit
fi

if [ -f $HOME/perl5/perlbrew/bin/cpanm ]; then
    echo "Remove perlbrew's cpanm"
    rm -f $HOME/perl5/perlbrew/bin/cpanm
fi

VERSION=$(perl -MConfig -e 'print $Config{version}')
echo "Install cpanm for perl-${VERSION}"
curl -L http://cpanmin.us | perl - App::cpanminus
