#!/usr/bin/env bash
set -e

PR_NUMBER=$1
BRANCH_NAME=$2

if [[ -z $PR_NUMBER ]]; then
    echo "Usage: pr-fetch PR-Number Branch-Name"
    exit 1
fi

if [[ -z $BRANCH_NAME ]]; then
    BRANCH_NAME="pr-$PR_NUMBER"
fi

printf "Fetch Pull Requst %s into %s\n" $PR_NUMBER $BRANCH_NAME
git fetch origin pull/${PR_NUMBER}/head:$BRANCH_NAME
