#!/bin/sh
set -e

EMACS="${EMACS:-emacs}"

SYSTEM=$(uname -s)
if [ "$SYSTEM" = "Darwin" ]; then
    EMACS="/Applications/Emacs.app/Contents/MacOS/Emacs"
fi

ELPA_DIR=$(env EMACS=${EMACS} cask package-directory)

TEST_CONFIG=${HOME}/dot_files/emacs/test_emacs

if [ -e "Cask" -a -d "${ELPA_DIR}" ]; then
    cask exec $EMACS -Q -l $TEST_CONFIG $@
else
    $EMACS -Q -l $TEST_CONFIG $@
fi
