#!/usr/bin/env zsh
set -e

ELPA_DIR=.cask/$(emacs -Q --batch --eval '(princ emacs-version)')/elpa

EMACS=""
case "$OSTYPE" in
darwin*)
    EMACS="/Applications/Emacs.app/Contents/MacOS/Emacs"
    ;;
linux-gnu)
    EMACS=emacs
    ;;
esac

TEST_CONFIG=${HOME}/dot_files/emacs/test_emacs

if [ -d "${ELPA_DIR}" ]; then
    cask exec $EMACS -Q -l $TEST_CONFIG $@
else
    $EMACS -Q -l $TEST_CONFIG $@
fi
